import os
import sys
import json
import logging
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

# Load env variables from root workspace or local file
load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env"))
load_dotenv()

# Map AI_STUDIO_API key to GEMINI_API_KEY for ADK 2.0
if "AI_STUDIO_API" in os.environ and "GEMINI_API_KEY" not in os.environ:
    os.environ["GEMINI_API_KEY"] = os.environ["AI_STUDIO_API"]

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("space-education-backend")

# Import ADK elements
try:
    from google.adk.runners import InMemoryRunner
    from google.adk.apps import App
    from agent_workflow import space_workflow, clean_json_string
except ImportError as e:
    logger.error(f"Failed to import google.adk: {e}")
    # We will let the app fail on startup if dependencies are missing,
    # but print a clear warning during building.

# FastAPI App
app = FastAPI(title="Space Education Agent API")

# Enable CORS for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # In production, restrict to frontend domain
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# API Request/Response Schemas
class ChatRequest(BaseModel):
    query: str

class ChatResponse(BaseModel):
    educational_response: str
    is_space_related: bool
    simulation_target: str | None = None
    simulation_url: str | None = None

# Initialize ADK App and Runner
try:
    adk_app = App(
        name="space_education_agent",
        root_agent=space_workflow
    )
    runner = InMemoryRunner(app=adk_app)
except Exception as e:
    logger.error(f"Failed to initialize ADK Runner: {e}")
    runner = None

import asyncio

@app.get("/api/health")
async def health_check():
    return {
        "status": "healthy",
        "has_runner": runner is not None,
        "has_gemini_key": "GEMINI_API_KEY" in os.environ,
        "has_nasa_key": "NASA_API" in os.environ
    }

@app.post("/api/chat", response_model=ChatResponse)
async def chat_endpoint(request: ChatRequest):
    if not runner:
        raise HTTPException(status_code=500, detail="ADK runner is not initialized.")
    
    if not os.environ.get("GEMINI_API_KEY"):
        raise HTTPException(status_code=500, detail="Gemini API Key is not configured on the backend.")

    logger.info(f"Processing query: {request.query}")
    
    max_attempts = 3
    delay = 2.0
    last_error = None
    
    for attempt in range(1, max_attempts + 1):
        try:
            logger.info(f"Executing agent workflow (Attempt {attempt}/{max_attempts})...")
            # Run the workflow
            events = await runner.run_debug(request.query, quiet=True)
            
            # Extract the final output
            final_text = ""
            for event in reversed(events):
                # Try to get text from content parts
                if event.content and event.content.parts:
                    text_parts = [p.text for p in event.content.parts if p.text]
                    if text_parts:
                        final_text = "".join(text_parts)
                        break
                # Fallback: check event message
                msg = getattr(event, "message", None)
                if msg:
                    final_text = msg
                    break
                    
            if not final_text:
                raise ValueError("No response generated by the agent workflow.")

            logger.info(f"Agent raw final output: {final_text}")

            # Parse the output JSON after cleaning it
            try:
                cleaned_text = clean_json_string(final_text)
                parsed_data = json.loads(cleaned_text)
                return ChatResponse(
                    educational_response=parsed_data.get("educational_response", ""),
                    is_space_related=parsed_data.get("is_space_related", True),
                    simulation_target=parsed_data.get("simulation_target"),
                    simulation_url=parsed_data.get("simulation_url")
                )
            except json.JSONDecodeError:
                # Fallback in case model outputs plain text instead of JSON
                logger.warning("Agent did not output valid JSON. Formatting response manually.")
                return ChatResponse(
                    educational_response=final_text,
                    is_space_related=True,
                    simulation_target=None,
                    simulation_url=None
                )
        except Exception as e:
            last_error = e
            logger.warning(f"Attempt {attempt} failed with error: {e}")
            if attempt < max_attempts:
                logger.info(f"Waiting {delay} seconds before retrying...")
                await asyncio.sleep(delay)
                delay *= 1.5  # Exponential backoff
            else:
                logger.error("All retry attempts exhausted.")
                
    logger.error(f"Error during agent execution: {last_error}", exc_info=True)
    raise HTTPException(status_code=500, detail=f"Error executing agent workflow: {str(last_error)}")

if __name__ == "__main__":
    import uvicorn
    # Allow running python main.py directly for development
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
